version: '3.9'
services:
  web:
    image: node:lts
    user: node
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - '4000:4000'
    volumes:
      - ./:/home/node/app
    command: >
      sh -c "chmod -R 777 /home/node/app &&
             npm start"
